# Generated by Django 3.1.1 on 2020-12-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0006_auto_20201210_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
