# Generated by Django 3.1.1 on 2020-12-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0010_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default=' ', null=True, upload_to=''),
        ),
    ]
