# Generated by Django 3.1.1 on 2020-12-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0014_wishitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitem',
            name='quantity_wish',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
