# Generated by Django 3.1.1 on 2020-12-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0015_wishitem_quantity_wish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='wishitem',
            name='quantity_wish',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
