# Generated by Django 3.1.1 on 2020-12-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0016_auto_20201224_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
